FROM node:16.18.1-buster

ARG CONTRACTS_REPO=surfingnerd
ARG CONTRACTS_COMMIT_HASH=7d53424907c116ba59a47c3270a431e0b53386d2
ARG NOTE_REPO_REPO=surfingnerd
ARG NODE_COMMIT_HASH=f0738f877253007bfa20614f6f9f6dfac2a9e4a4
ARG TESTING_REPO=surfingnerd
ARG TESTING_COMMIT_HASH=c28bab0f69997a3d018b09534dfaafd60d0ad22f

RUN apt-get update && apt-get upgrade -y && apt-get install apt-utils git-core curl cmake net-tools zsh -y
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# contracts
RUN cd /root && git clone https://github.com/$CONTRACTS_REPO/hbbft-posdao-contracts.git && cd hbbft-posdao-contracts && git checkout $CONTRACTS_COMMIT_HASH
RUN cd /root/hbbft-posdao-contracts && npm ci && npm run compile && mkdir -p build/contracts && find artifacts/**/*.sol/*json -type f -exec cp '{}' build/contracts ';' && cd ..

# open ethereum
RUN cd /root && git clone https://github.com/$NOTE_REPO_REPO/diamond-node.git && cd diamond-node && git checkout $NODE_COMMIT_HASH
RUN cd /root/openethereum && . "$HOME/.cargo/env" &&  rustup default 1.64 && RUSTFLAGS='-C target-cpu=native' && cargo build --release && cd ..

# honey badger testing
# RUN cd openethereum-3.x &&  RUSTFLAGS='-C target-cpu=native' && cargo build --release && cd ..
RUN cd /root && git clone https://github.com/$TESTING_REPO/honey-badger-testing.git && cd honey-badger-testing && git checkout $TESTING_COMMIT_HASH
RUN cd /root/hbbft-posdao-contracts && mkdir -p build/contracts && find artifacts/contracts -name "*.json" -exec cp '{}' /root/hbbft-posdao-contracts/build/contracts/ ';'
RUN rm /root/hbbft-posdao-contracts/build/contracts/*.dbg.json
RUN cd /root/honey-badger-testing && . "$HOME/.cargo/env" && npm ci
RUN cd /root/honey-badger-testing && . "$HOME/.cargo/env" && npm run build-open-ethereum
RUN cd /root/honey-badger-testing && npm run 
RUN cd /root/honey-badger-testing && . "$HOME/.cargo/env" && npm run testnet-fresh
# honey badger testing

